version: '3.8'
services:
  backend:
    build: ./backend
    container_name: vacchuncc_backend
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - mysql_network
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    container_name: vacchuncc_frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
      - /app/node_modules

  mysql:
    container_name: vacchuncc_mysql
    image: mysql:9.0.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: vacchuncc
    ports:
      - 3306:3306
    networks:
      - mysql_network
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  phpmyadmin:
    container_name: vacchuncc_pma
    depends_on:
      - mysql
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: example
    networks:
      - mysql_network
networks:
  mysql_network:
