version: '3.8'

services:
  mysql:
    container_name: vacchuncc_mysql
    image: mysql:9.0.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: vacchuncc
    ports:
      - 3306:3306
    networks:
      - mysql_network
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  
  backend:
    build: ./backend
    container_name: vacchuncc_backend
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - mysql_network
    depends_on:
      mysql:
        condition: service_healthy
    command: sh -c "sleep 30 && npm start"
    
  apache:
    build:
      context: .
      dockerfile: apache/Dockerfile
    container_name: vacchuncc_apache
    ports:
      - 80:80
      - 443:443
    networks:
      - mysql_network

  phpmyadmin:
    container_name: vacchuncc_pma
    depends_on:
      - mysql
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: example
    networks:
      - mysql_network

networks:
  mysql_network:

volumes:
  mysql_data:
